/*! Google Drive APIs v3 | CC0 3Ds - Free 3D Models Under Public Domain | cc03ds.com/p/license.html */
function kitchenset_blend(){window.open('https://www.googleapis.com/drive/v3/files/1NQzNH-rp0lYRe2E1QpSaSZOOscNKom14?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function kitchenset_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1uYADVnJ6eAGBUbZddtAmmjBffJKL_HMf?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function kitchenset_obj(){window.open('https://www.googleapis.com/drive/v3/files/1vkt3vjfA7KgAywbw1eyMpVbKadr4f4QO?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function kitchenset_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1aU5mRXRa02uQ1rzMSFatSZGCU2VvdOja?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function kitchenset_dae(){window.open('https://www.googleapis.com/drive/v3/files/17rfc6EyvOT0GqkLzQoKsYOBF0OQ-fnKr?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function kitchenset_stl(){window.open('https://www.googleapis.com/drive/v3/files/11w0xmtfBaCCq1q5zPzWK7v017U3o3AWS?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function sr2xhdprime_blend(){window.open('https://www.googleapis.com/drive/v3/files/12GpCr8ZhMy6ZQwS9tqdnHzCYw6FoNWrw?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function sr2xhdprime_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1zM4N9m_eK_snc1ncLCDOFIHURZ8hYu7V?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function sr2xhdprime_obj(){window.open('https://www.googleapis.com/drive/v3/files/1lz55IB4JEeVWU8tkn6rddvykfgkyfRPC?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function sr2xhdprime_dae(){window.open('https://www.googleapis.com/drive/v3/files/17mivk8MomUcQSQTpjLGLpxR73LnqLNOk?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function sr2xhdprime_stl(){window.open('https://www.googleapis.com/drive/v3/files/1smPpygTYP_xHi3-e42JSqDfHAWv8y9AP?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function fusosupergreat_blend(){window.open('https://www.googleapis.com/drive/v3/files/1oyfq2S5P4gnwEHnEnqMup7wfQyiCRojm?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function fusosupergreat_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1i2toUPjbjFKKbT0pHSEB0kCoKaytuL9d?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function fusosupergreat_obj(){window.open('https://www.googleapis.com/drive/v3/files/1AC68LghABMwdmzVAoE3LF5-2VrHVnrN2?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function fusosupergreat_dae(){window.open('https://www.googleapis.com/drive/v3/files/1gD24InJ2XkVsNvml36tUB0jtob5OIM8C?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function fusosupergreat_stl(){window.open('https://www.googleapis.com/drive/v3/files/14RJtRwoTi9cPF4-_G8Lsg5BGeggYyl2R?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function rubberducky_blend(){window.open('https://www.googleapis.com/drive/v3/files/1wxq3cQVo2XJY3epiY33rJQ2DktcXS6vm?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function rubberducky_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1JnYY-VLOetihQdu4F2HkJx-dgO-faGzA?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function rubberducky_obj(){window.open('https://www.googleapis.com/drive/v3/files/1-RZaNlKgQmcQsGqj_BihIHHrOa7ywh3K?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function rubberducky_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1OMot7J_A88F4p0hGzRDE9dGMj1C141S8?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function rubberducky_dae(){window.open('https://www.googleapis.com/drive/v3/files/15PZGnnikYn2WCEXmGeZDoVDSOPyQPwQ-?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function rubberducky_stl(){window.open('https://www.googleapis.com/drive/v3/files/1Y-VE4YpVDlnUIgMor6CVqn9dIpZ9J1_M?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function apple_blend(){window.open('https://www.googleapis.com/drive/v3/files/1A_FZj7ve9yBlz8NE7-2Iu5Qi_9gEJQf5?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function apple_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1MSGZTmQrZxCynTl9vGANkHDK7hXTZHzO?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function apple_obj(){window.open('https://www.googleapis.com/drive/v3/files/1dzPK86I8zCTuCPyQTdfyedKRVFGOnAu2?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function apple_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1q4Kax2KCNkkbK_6TFr09WTnBMH5McxaX?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function apple_dae(){window.open('https://www.googleapis.com/drive/v3/files/1IsFRhELwYH3BrkU1AT633muDItzZ3oKp?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function apple_stl(){window.open('https://www.googleapis.com/drive/v3/files/19LwfGi7T8IqBirMcyujavFkv0dxeT8PR?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function coltdieselfe74_blend(){window.open('https://www.googleapis.com/drive/v3/files/1RtCitw94qj2CNgtn7Z78ecpETEVXRZoT?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function coltdieselfe74_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1x-xaP8YvFfEFu98xGW1XjcMpZZEhy2Fj?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function coltdieselfe74_obj(){window.open('https://www.googleapis.com/drive/v3/files/1IAar3pnJ3baMJoajHV4CiTzumAsLV985?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function coltdieselfe74_dae(){window.open('https://www.googleapis.com/drive/v3/files/1mq8h8SxXVxRjMI0RiLwBsKrRpJdfEmRt?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function coltdieselfe74_stl(){window.open('https://www.googleapis.com/drive/v3/files/1wfv41qC-Mtqb7MvCOaRs67ZVXif4xKxU?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function tablelamp_blend(){window.open('https://www.googleapis.com/drive/v3/files/15ecwQo3m08XDseOefWDsZ5bkpD9f4bXi?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function tablelamp_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1hLq7Vdao5GRAxUQS1yae8RBn0csD7ZT6?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function tablelamp_obj(){window.open('https://www.googleapis.com/drive/v3/files/1aJds0tC2SmPRRakaAxBZ2wUIEbePERrS?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function tablelamp_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1sDrQCW3SdTu5bKWFsGtbrqy70Q81EDTC?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function tablelamp_dae(){window.open('https://www.googleapis.com/drive/v3/files/1noqV4ofTnQ7WJDoHKvkw50OVsitFPSVB?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function tablelamp_stl(){window.open('https://www.googleapis.com/drive/v3/files/1Rg0kMnNxzpS1vezEQsdTZrOT85-b0CZX?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggone1_blend(){window.open('https://www.googleapis.com/drive/v3/files/192gZjNfM6UttW4H_NVXvnYNWhXTfeK1y?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggone1_fbx(){window.open('https://www.googleapis.com/drive/v3/files/18sPghtcocP0ORMMQO5kqMDQeyKDYRIhx?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggone1_obj(){window.open('https://www.googleapis.com/drive/v3/files/1uWZs5zoemULLB3Hb1t0FiZ_Um-tYBZkK?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggone1_dae(){window.open('https://www.googleapis.com/drive/v3/files/1U70E5yy1IztsDDaMWJFuVHbVRhVLLawV?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggone1_stl(){window.open('https://www.googleapis.com/drive/v3/files/1WoFd-SclLV_qikoW0WwCAIEDcTh21ksK?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function nissanquestergke280_blend(){window.open('https://www.googleapis.com/drive/v3/files/1wEridBFS4SUlrmEESaanWlZ9zsKh6ZY_?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function nissanquestergke280_fbx(){window.open('https://www.googleapis.com/drive/v3/files/18AOdb5yfQJIY8t9bTA1UYN8jaAOQ7Rw1?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function nissanquestergke280_obj(){window.open('https://www.googleapis.com/drive/v3/files/109w-nkOgNPcH82Zqvx_X1GtIWQbuvfbW?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function nissanquestergke280_dae(){window.open('https://www.googleapis.com/drive/v3/files/1WIk60LXH8T_-_k4UJ55TnhHa3Aw-TVaN?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function nissanquestergke280_stl(){window.open('https://www.googleapis.com/drive/v3/files/1vKJorugpRfstcNZjgDzQGJMlMRt40sm8?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function teapot_blend(){window.open('https://www.googleapis.com/drive/v3/files/1ylSN0QOT8_RuGbJ9vcd3WUaesxqBjcZ6?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function teapot_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1PVpj5f9NBYOt0XSAE0zwTNYiY7e7x0Tg?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function teapot_obj(){window.open('https://www.googleapis.com/drive/v3/files/1iHGVKBq2u4VDRPszAnby1LlI_uYcu4L_?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function teapot_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1PWJaBSWqHwPe6HMjzcYzqwiB7xymb7uC?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function teapot_dae(){window.open('https://www.googleapis.com/drive/v3/files/1t9S0J5Uy8iZmY07rLEmmqRySGjaRaxua?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function teapot_stl(){window.open('https://www.googleapis.com/drive/v3/files/1c9JfJ8ztZEdzR8-46AvX5M2aFWyNDw6a?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function woodchair_blend(){window.open('https://www.googleapis.com/drive/v3/files/1wV79i2voU5yVs51YZ_nrQWKbwklnAdvt?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function woodchair_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1NkwlC5Zb6VOweN347-i-PcnyTj5NNqVt?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function woodchair_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1Cr7cv8yOAyZudeqJTcO4eBCwhx-UCY_B?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function woodchair_dae(){window.open('https://www.googleapis.com/drive/v3/files/1iKd5rrc9-ZjYVxriQHozof-iYt_pizj4?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function woodchair_stl(){window.open('https://www.googleapis.com/drive/v3/files/1ZsYHpuM0BtOhq_J3v5ONIP6wmOMXHKRo?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function oreosupreme_blend(){window.open('https://www.googleapis.com/drive/v3/files/1X_iBf9xPayMGuLT-4KXPgwfYwqQ9N_a4?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function oreosupreme_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1OObEHRXacd7RnRwtRUzz0MCV1oo20g3v?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function oreosupreme_obj(){window.open('https://www.googleapis.com/drive/v3/files/1p2VZyakPnjtr1o82tambTdV6ur8Eriih?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function oreosupreme_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1fdszXuAX6EZqYoOfhNS5KaBL-IMYpOma?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function oreosupreme_dae(){window.open('https://www.googleapis.com/drive/v3/files/1AzwZUJKhKfjBl-ZQt1jGmULmpnOy1CE9?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function oreosupreme_stl(){window.open('https://www.googleapis.com/drive/v3/files/1GbXiDx3kCZeCCoRQpevirOyAtznzr3ut?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function mugs_blend(){window.open('https://www.googleapis.com/drive/v3/files/1JsgvHdCTK8YIJ1EqFggfbF1PBquDZEmv?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function mugs_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1FFZUe8qpZXvVMW8RcZoORqChbmvCk0ia?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function mugs_obj(){window.open('https://www.googleapis.com/drive/v3/files/1GamKiuC0cJQceLWCuurmucjGnncq9sWy?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function mugs_3ds(){window.open('https://www.googleapis.com/drive/v3/files/1hDk1G6hQVjCnfPisdI_fl7Hfe4D2r6UK?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function mugs_dae(){window.open('https://www.googleapis.com/drive/v3/files/1LAXm6f_rOE4pa2RKxydhHPyuJhnUa-8F?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function mugs_stl(){window.open('https://www.googleapis.com/drive/v3/files/1UrG_70GxgC-Ot1puymRKHgjACjX7_QDp?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggregera_blend(){window.open('https://www.googleapis.com/drive/v3/files/1I-CafDszAjBWsdAZpSfKStfP_-dcTOu8?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggregera_fbx(){window.open('https://www.googleapis.com/drive/v3/files/1zDHHf9cr0TYRzKM4jdBG1Vboaer4u8Nm?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggregera_obj(){window.open('https://www.googleapis.com/drive/v3/files/1mMSc2PT0vzcgt_hSX4m5mHex_v5ARCXW?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggregera_dae(){window.open('https://www.googleapis.com/drive/v3/files/1Uj7WLlL6zVEr83mVAeqpIXu-r7BfK-Je?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function koenigseggregera_stl(){window.open('https://www.googleapis.com/drive/v3/files/1AjmEwufKlxEthMkUCXe9-s9F7IfAmZYs?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function _blend(){window.open('https://www.googleapis.com/drive/v3/files/?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function _fbx(){window.open('https://www.googleapis.com/drive/v3/files/?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function _obj(){window.open('https://www.googleapis.com/drive/v3/files/?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function _3ds(){window.open('https://www.googleapis.com/drive/v3/files/?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function _dae(){window.open('https://www.googleapis.com/drive/v3/files/?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
function _stl(){window.open('https://www.googleapis.com/drive/v3/files/?alt=media&key=AIzaSyB6GD77XU6gxgNtQGTXH_mPcSd7jLRC_IM');}
